sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - chmod +x mvnw
  - mvn clean verify package

after_success:
  - chmod -R 777 push-to-docker.sh
  - push-to-docker.sh