sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - chmod +x mvnw
  - mvn clean verify package
  - docker build -t storezhang/cash-agent .
  - docker run storezhang/cash-agent

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push storezhang/cash-agent;
    fi