cash:
  retry: 3
  zpp:
    minCash: 5
    users:
      - username: storezhang@gmail.com
        password: xtkthh13284@$
  mayi:
    minCash: 1
    users:
      - username: storezhang
        password: xtkthh13284#%